---
- hosts: web
  become: yes
  gather_facts: yes
  roles:
    - role: webserver  
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - role: users
    - role: install
